config/routes.rb
Rconerre::Application.routes.draw do

  get "admin/users"

  get "content/videos"

  devise_for :users

  root :to => 'static_pages#home'

  match '/about' => 'static_pages#about'

  match '/contact' => 'static_pages#contact'

  match '/help' => 'static_pages#help'

  match "/buy" => "static_pages#buy"

  match "/videos" => "content#videos"

  match "/terms" => "static_pages#terms"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :user_id
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def users
  	@all_users = User.all
  	@admin_user_question = Admin.where(user_id: current_user.id)[0].nil? ? false : true
  		if @admin_user_question == false
  			redirect_to root_path
  		end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(users)
  	videos_path
  end
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def videos
  	@paid_client = Client.where(user_id: current_user.id)[0].nil? ? false : true 
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def buy
  end

  def help
  end

  def terms
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  #GET /resource/sign_up
  #def new
    #super
  #end

  #POST /resource
  #def create
    #super
    #redirect_to videos_path
  #end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/users.html.erb
<div class="box_centered">
	<h2>Usuarios R Con Erre</h2>
	<% @all_users.each do |u| %>
		<p><%= u.id %> - <%= u.email %> - Creado: <%= u.created_at.day %> de <%= u.created_at.month %> de <%= u.created_at.year %> | Último inicio de sesión: <%= u.last_sign_in_at.day %> de <%= u.last_sign_in_at.month %> <%= u.last_sign_in_at.year %> </p>
	<% end %>
</div>

app/views/content/videos.html.erb
<h1>Content#videos</h1>
<% if @paid_client %>
	<h2>Aquí están los videos</h2>
<% else %>
	<h2>Compra aquí para ver el contenido</h2>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
	R con Erre © 2014 
	<%= link_to "Contacto", contact_path %>
	<a href="http://facebook.com/Rconerre">Facebook</a>
	<a href="http://twitter.com/rconerremx">Twitter</a>
	<a href="http://blog.rconerre.mx">Blog</a>
</div>

app/views/layouts/_header.html.erb
<div class="header">
	<%= link_to "Inicio", root_path %>
	<%= link_to "Nosotros", about_path %>
	<%= link_to "Producto", buy_path %>
	<%= link_to "Ayuda", help_path %>
	<% if user_signed_in? %>
		<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Iniciar sesión", new_user_session_path, class: "sign-in" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
	<title>Rconerre</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	 <% flash.each do |name, msg| %>
     	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
</body>
</html>
  

app/views/static_pages/about.html.erb
<div class="buy-cover">
	<h2>Porque comunicarse es lo más importante.</h2>
	<p>Trabajamos para que la terapia de lenguaje sea sencilla, alcanzable y efectiva para todos.</p>
</div>

<div class="nosotros">
	<h2>Facilitamos la terapia de lenguaje</h2>
		<div class="nosotros-centered">
			<div class="nosotros-box">
				<img alt="atencion" src="/assets/atencion.png" hspace="40"/>
				<h3>Sobre nosotros</h3>
				<p>Somos terapeutas de lenguaje profesionales y buscamos compartir nuestro conocimiento con los padres de familia.</p>
			</div>

			<div class="nosotros-box">
				<img alt="comodidad" src="/assets/comodidad.png" hspace="40"/>
				<h3>Tutoriales únicos</h3>
				<p>Desarrollamos los únicos tutoriales en video de terapia de lenguaje, para que los padres puedan guiar y enseñar a sus hijos desde casa.</p>
			</div>

			<div class="nosotros-box">
				<img alt="cercania" src="/assets/cercania.png" hspace="40"/>
				<h3>Nuestra meta</h3>
				<p>Trabajamos todos los días para realizar tutoriales cada vez más sencillos y efectivos.</p>
			</div>

			<div class="nosotros-box">
				<img alt="precio" src="/assets/precio.png" hspace="40"/>
				<h3>Precio</h3>
				<p>Paga una sola vez y recibe más de 50 videos tutoriales y un diagnóstico personalizado.</p>
			</div>
	</div>
</div>

<div class="about-photo">
	<h1>Tenemos lo que necesitas</h1>
	<h2>para que tu hijo desarrolle su lenguaje.</h2>
	<div class="main-buy-button-margin">
	<%= link_to "COMIENZA HOY", buy_path, class: "main-buy-button" %>
	</div>
</div>

app/views/static_pages/buy.html.erb
<div class="buy-cover">
	<h2>Terapia de lenguaje desde casa.</h2>
	<p>Desarrollamos tutoriales en video para estimular y desarrollar el lenguaje de tus hijos.</p>
</div>

<div class="ventajas">
	<h2>Nuestro Producto</h2>
		<div class="box-centered">
			<div class="ventajas-box">
				<img alt="atencion" src="/assets/atencion.png" hspace="40"/>
				<h3>Atención profesional</h3>
				<p>Tutoriales diseñados por psicólogos profesionales especialistas en terapia de lenguaje.</p>
			</div>

			<div class="ventajas-box">
				<img alt="comodidad" src="/assets/comodidad.png" hspace="40"/>
				<h3>Comodidad</h3>
				<p>Consulta nuestros tutoriales desde casa o en cualquier dispositivo móvil con acceso a Internet.</p>
			</div>

			<div class="ventajas-box">
				<img alt="cercania" src="/assets/cercania.png" hspace="40"/>
				<h3>Cercanía</h3>
				<p>Guía y acompaña a tu hijo durante este proceso tan importante.</p>
			</div>

			<div class="ventajas-box">
				<img alt="precio" src="/assets/precio.png" hspace="40"/>
				<h3>Precio</h3>
				<p>Paga una sola vez y recibe más de 50 videos tutoriales y un diagnóstico personalizado.</p>
			</div>
	</div>
</div>

<div class="payments">
	<h2>Planes de pago</h2>
			<div class="payments-box">
				<h3>Adquiere nuestro plan único y recibe:</h3>
				<div class="payment-feature">
					<img alt="video" src="/assets/video.png"/>
					<p>Acceso ilimitado a tutoriales en video.</p>
				</div>	

				<div class="payment-feature">
					<img alt="check" src="/assets/check.png"/>
					<p> Diagnóstico inicial personalizado.</p>
				</div>

				<div class="payment-feature">
					<img alt="smiley" src="/assets/smiley.png"/>
					<p> Atención y soporte profesional.</p>
				</div>

					<div class="payment-feature">
					<img alt="pen" src="/assets/pen.png"/>
					<p> Acceso ilimitado a nuestro Blog.</p>
				</div>

				<div class="payment-button-marginer">
					<a href="#" class="payment-button">$960.00</a>
				</div>
			</div>
</div>

<div class="transferencia">
	<h2>Pago con transferencia bancaria</h2>
	<p>Si prefieres hacer tu pago con transferencia bancaria, ponte en contacto con nosotros.</p>

app/views/static_pages/contact.html.erb
<h1>S</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<div class="buy-cover">
	<h2>¿Preguntas?</h2>
	<p>Estamos aquí para resolver todas tus dudas.</p>
</div>

<div class="help-2">
	<h2>Queremos ayudarte</h2>
		<div class="help-centered">
			<div class="help-box">
				<img alt="phone" src="/assets/phone.png" hspace="40"/>
				<h3>Atención telefónica</h3>
				<p>Habla con nuestro equipo de soporte y obtén asesoría personalizada.</p>
			</div>

			<div class="help-box">
				<img alt="talk" src="/assets/question.png" hspace="40"/>
				<h3>Atención electrónica</h3>
				<p>Mándanos un mensaje y un miembro de nuestro equipo  te contestará a la brevedad.</p>
			</div>

			<div class="help-box">
				<img alt="medal" src="/assets/medal.png" hspace="40"/>
				<h3>Disponibilidad</h3>
				<p>Estamos siempre disponibles para ayudarte en caso de alguna duda o dificultad.</p>
			</div>

			<div class="help-box">
				<img alt="salvavidas" src="/assets/salvavidas.png" hspace="40"/>
				<h3>¿Preguntas?</h3>
				<p>Revisa nuestra sección de preguntas frecuentes y encuentra la respuesta que buscas.</p>
			</div>
	</div>
	</div>
</div>

<div class="faq">
	<h2>Preguntas frecuentes</h2>

	<h3>¿Qué es R Con Erre?</h3>
	<p>R con Erre es una aplicación que contiene tutoriales en video dedicados a estimular y desarrollar el lenguaje de los niños, dando herramientas a los padres para que guíen y enseñen a sus hijos a comunicarse y expresarse mejor.</p>

	<div class="purple-line"></div>
	<h3>¿Quién puede usar R Con Erre?</h3>
	<p>R Con Erre está dirigido a niños de 2 a 10 años de edad, que presentan alguna dificultad en el lenguaje. Ya sea omitiendo, cambiando o sustituyendo algún sonido del habla.</p>

	<div class="purple-line"></div>
	<h3>¿Cómo funciona R Con Erre?</h3>
	<p>Al adquirir nuestro programa, tendrás acceso anual a nuestros videos tutoriales y a una evaluación inicial personalizada, la cual será tu guía para estimular el lenguaje de tu hijo.</p>

	<div class="purple-line"></div>
	<h3>¿Cómo puedo realizar mi pago?</h3>
	<p>Dirígete a nuestra sección de <%= link_to "compra", buy_path, style: "color: black; font-weight: 700" %> y realiza tu pago con tarjeta de crédito o PayPal. También puedes realiza un depósito bancario directo.</p>

	<div class="purple-line"></div>
	<h3>¿Por cuánto tiempo tendré acceso a los tutoriales?</h3>
	<p>Nuestro plan actual es anual. Una vez realizado tu pago, tendrás acceso ilimitado a nuestros tutoriales. Practica y realiza los ejercicios con tu hijo todo el tiempo que necesites.</p>

	<div class="purple-line"></div>
	<h3>¿Dónde puedo ver los tutoriales?</h3>
	<p>Puedes acceder a nuestros tutoriales desde cualquier computadora, laptop, Ipad, Tableta, Iphone o Smartphone con conexión a Internet.</p>

	<div class="purple-line"></div>
	<h3>¿Puedo descargar los tutoriales?</h3>
	<p>No. Únicamente puedes acceder a los tutoriales desde nuestro sitio web.</p>

	<div class="purple-line"></div>
	<h3>¿Puedo acceder a los tutoriales sin conexión a Internet?</h3>
	<p>No.</p>

	<div class="purple-line"></div>
	<h3>¿Por cuánto tiempo se deben practicar los tutoriales?</h3>
	<p>Recomendamos que la práctica sea constante, con una duración en promedio de 30 minutos por día, ya que entre más estimulación reciba el niño, su avance será mayor y más rápido.</p>

	<div class="purple-line"></div>
	<h3>¿Mi hijo puede practicar por su cuenta?</h3>
	<p>No. Nuestros tutoriales están hechos específicamente para que los niños reciban estimulación con ayuda de sus papás o un adulto.</p>

	<div class="purple-line"></div>
	<h3>¿Qué letras incluyen los tutoriales de R Con Erre?</h3>
	<p>Incluímos todos los sonidos del habla (letras) del idioma español.</p>

	<div class="purple-line"></div>
	<h3>¿R Con Erre sustituye a la terapia de lenguaje tradicional?</h3>
	<p>Buscamos ser una herramienta de apoyo a la terapia tradicional. Si tu hijo presenta una alteración de lenguaje, sería importante que consultes con un especialista -ya sea médico o terapeuta de lenguaje- para recibir un diagnóstico formal y posteriormente adquirir nuestro programa.</p>

	<div class="purple-line"></div>
	<h3>¿Necesito un diagnóstico médico para utilizar R Con Erre?</h3>
	<p>No, no es necesario, cualquier persona puede utilizar R Con Erre. Sin embargo, es importante consultar con un especialista para que revise y diagnostique correctamente a tu hijo.</p>

	<div class="purple-line"></div>
	<h3>¿R Con Erre funciona para trastornos de disfemia (tartamudez)?</h3>
	<p>No, por el momento nuestros tutoriales se enfocan únicamente en trastornos de omisión, sustitución y articulación incorrecta de letras.</p>

	<div class="purple-line"></div>
	<h3>¿R Con Erre tiene límite de edad?</h3>
	<p>Nuestro programa está diseñado para niños de 2 a 10 años, sin embargo, cualquiera puede utilizar nuestros tutoriales para estimular y desarrollar su lenguaje.</p>
	
	<div class="purple-line"></div>
	<h3>¿Quién es R Con Erre?</h3>
	<p>Somos una compañía independiente con base en Monterrey, Nuevo León, México. Pasamos nuestro tiempo mejorando nuestro sitio, resolviendo las dudas de nuestros usuarios y encontrando nuevas maneras de mejorar e innovar la terapia de lenguaje.</p>

</div>
 

app/views/static_pages/home.html.erb
<div class= "home-cover">
	<h1>Terapia de lenguaje desde casa</h1>
	<h2>Tutoriales que estimulan y desarrollan el lenguaje de tus hijos.</h2>
	<div class="main-buy-button-margin">
	<%= link_to "COMIENZA HOY", buy_path, class: "main-buy-button" %>
	</div>
</div>